import Footer from "./components/elements/Footer";
import Header from "./components/elements/Header";
import "./globals.css";
import "bootstrap/dist/css/bootstrap.min.css";

// import 'bootstrap/dist/js/bootstrap.bundle';

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body>
        <div
          className="d-flex justify-content-between flex-column"
          style={{ minHeight: "100vh" }}
        >
          <Header />
          {children}
          <Footer />
        </div>
      </body>
    </html>
  );
}
